# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24c3d74a92905c686ec608b9c4f4f0704550c2b65c805fb7eea3133cd4afb5c896b8ad76c7d2a16f8bf4b366a1912bbc65d68c17b7af9f3522272f5cec8113be

test:
  secret_key_base: 6a3be8a8bdfad22b8d2465ceee066afc0f3fc506e1b095576eecbcf4b3c1d703507703191b968550a8a38ae98c33b6d332dd9a7fe684e1f78ef181bff86e2427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
